language: php

php:
  - 7.2
  - 7.3

sudo: true

env:
  global:
    - PHPCS=0
    - RUN_TESTS=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 RUN_TESTS=0

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.4.deb && sudo service elasticsearch restart

install:
  - composer install

before_script:
  - sleep 7 # Work around elasticsearch startup time.

script:
  - if [[ $RUN_TESTS == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p ./src ./tests; fi

notifications:
  email: false
